# Load in NumPy:

In [1]:
import numpy as np

## The Basics
1D array

In [2]:
a=np.array([1,2,3])
print(a)

[1 2 3]


2D array

In [ ]:
b=np.array([[1,2,3,4],[5,6,7,8]]) #array of array
print(b)

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
#get dimension
print(a.ndim,b.ndim)

1 2


In [ ]:
#get Shape
a.shape #(3,) since 1D
b.shape #(2,4)

(2, 4)

In [ ]:
#get type
a.dtype #64bit integer
b.dtype

dtype('int64')

In [ ]:
#get Size
a.size #Total number of elements 
b.size

8

In [ ]:
a.itemsize #size of each element in array in bytes
b.itemsize

8

Accessing/Changing specific elements, rows, columns, etc

In [67]:
a1=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a1)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [23]:
a1.shape

(2, 7)

In [26]:
#get specific element
a1[1,5]

np.int64(13)

In [29]:
#get a specific row
a1[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [30]:
#get a specific column
a1[:,2]

array([ 3, 10])

In [39]:
#more fancy
#array[startIndex,endIndex:stepSize]
a1[0,1:6:3]

array([2, 5])

In [42]:
#these are mutable
a1[1,4]=20 #change specific element
print(a1)

a1[:,2]=[1,2] #changing colunm
print(a1)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 20 13 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 20 13 14]]


In [43]:
#3D example
b1=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b1)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [46]:
#get specific element
b1[1,1,0]

np.int64(7)

In [53]:
#accessing differently
b1[1,1,:]

array([7, 8])

In [ ]:
#replace
#we can replace elements by accessing them individually or similar to 2d arrays

Initializing Different Types of Arrays

In [61]:
#all zeroes
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [62]:
#all ones
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [63]:
#different numbers
np.full((2,3),69)

array([[69, 69, 69],
       [69, 69, 69]])

In [65]:
#different numbers and dtype
np.full((2,3),69,dtype='int32')

array([[69, 69, 69],
       [69, 69, 69]], dtype=int32)

In [ ]:
np.full_like(a1,4) #changes all elements of a1 to 4

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [70]:
np.full(a1.shape,5) #similar like previous one but a bit different

array([[5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5]])

In [72]:
# random numbers
np.random.rand(4,2,3)

array([[[0.88437703, 0.8707302 , 0.52402146],
        [0.71648794, 0.51532065, 0.76184078]],

       [[0.31117361, 0.56551278, 0.09441374],
        [0.32501039, 0.37865316, 0.51147411]],

       [[0.1937406 , 0.26639164, 0.89753969],
        [0.99244567, 0.93163902, 0.36996068]],

       [[0.0848537 , 0.08458306, 0.44182066],
        [0.51598635, 0.12923104, 0.07900297]]])

In [73]:
np.random.random_sample(a1.shape)

array([[0.65467421, 0.55915598, 0.91672622, 0.16898839, 0.32243371,
        0.05930401, 0.08602163],
       [0.80078741, 0.14515331, 0.63773618, 0.39434829, 0.00109997,
        0.15853785, 0.1064587 ]])

In [76]:
np.random.randint(50,size=(2,3)) #50=>range of random integers size=>size of array
np.random.randint(50,69,size=(2,3)) #50-69 range

array([[55, 66, 67],
       [66, 52, 52]], dtype=int32)

In [ ]:
#identity matrix 
np.identity(4) #available for only 2d square matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [81]:
#repeating an array
arr=np.array([1,2,3])
r1=np.repeat(arr,3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [85]:
arr=np.array([[1,2,3]]) #2d array
r1=np.repeat(arr,3,axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [86]:
arr=np.array([[1,2,3]]) #2d array
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [94]:
#exercise
output=np.ones((5,5))
print(output)

z=np.zeros((3,3))
print(z)

z[1,1]=9
print(z)

output[1:4,1:-1]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [96]:
#Be carefull while copying 
x=np.array([1,2,3])
y=x #by doing this x and y points towards same address thereby changing one causes change in both
print(x,y)
y[1]=69
x[2]=55
print(x,y) 

[1 2 3] [1 2 3]
[ 1 69 55] [ 1 69 55]


In [97]:
#Be carefull while copying 
x=np.array([1,2,3])
y=x.copy() #use copy instead
print(x,y)
y[1]=69
x[2]=55
print(x,y) 

[1 2 3] [1 2 3]
[ 1  2 55] [ 1 69  3]


In [98]:
a=np.array([1,2,3,4])

In [ ]:
a+2 #add 2 with each element similar for -,*,/,**

array([3, 4, 5, 6])

In [ ]:
np.sin(a) #cos,tan...

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

##### Linear Algebra

In [109]:
a=np.ones((2,3))
b=np.full((3,2),2)

np.matmul(a,b) #does matrix multiplication

array([[6., 6.],
       [6., 6.]])

In [110]:
c=np.identity(3)
np.linalg.det(c) #linear algebra se determinant of c

np.float64(1.0)

Statistics

In [111]:
stats=np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [118]:
np.min(stats)
np.min(stats,axis=1)

array([1, 4])

In [113]:
np.max(stats)

np.int64(6)

In [121]:
np.sum(stats) #sum of all elements of array
np.sum(stats,axis=0)

array([5, 7, 9])

In [ ]:
#Reorganising arrays
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after=before.reshape((1,8)) #can be reshaped into any combination as long as the total elements remain same
after

#we have stack -> vstack() and hstack()

[[1 2 3 4]
 [5 6 7 8]]


array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [124]:

# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# Horizontal  stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

Miscellaneous
Load Data from File

In [130]:

filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


BOolean Masking and Advance Indexing

In [ ]:
filedata>50
filedata[filedata>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [134]:
np.any(filedata>50,axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [135]:
((filedata>50)&(filedata<100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])